version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.14
    working_directory: ~/src

    steps:
      - checkout

      - run:
          name: Configuration
          command: |
            git config --global user.email "nilsen.sondre@gmail.com"
            git config --global user.name "Sondre Nilsen"

      - run:
          name: Update NPM
          command: "sudo npm install -g npm@latest"

      - run:
          name: Authenticate NPM
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

      - restore_cache:
          name: Restore NPM Package Cache
          keys:
            - dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install Dependencies
          command: |
            npm ci
            npm run bootstrap --ci

      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Publish packages
          command: npm run ci:publish
