name: pipeline

on: [push, pull_request]

jobs:
  pipeline:
    name: pipeline
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.19.0

      - uses: actions/setup-node@v3
        with:
          node-version: "17"
          cache: "pnpm"

      - name: Install and build
        run: pnpm install

      - name: Lint
        run: |
          pnpm run lint
          pnpm run style
