name: pipeline

on:
  push:
    branches:
      - master

jobs:
  pipeline:
    env:
      CI: true
    name: pipeline
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and build
        run: yarn install --frozen-lockfile

      - name: Lint
        run: |
          yarn lint
          yarn style
  publish:
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    needs: pipeline
    env:
      CI: true
    name: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Configure Git, NPM
        run: |
          git config --global user.email "nilsen.sondre@gmail.com"
          git config --global user.name "Sondre Nilsen" 
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Prepare repository
        run: |
          git checkout "${GITHUB_REF:11}"
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GH_TOKEN }}

      - name: Publish
        run: |
          yarn install --frozen-lockfile
          yarn ci:publish
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_GH_TOKEN }}
