name: pipeline

on: [push, pull_request]

jobs:
  pipeline:
    name: pipeline
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4.2.0

      - uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: "pnpm"

      - name: Install and build
        run: pnpm install

      - name: Lint
        run: pnpm run format
