name: publish

on:
  push:
    branches:
      - master

jobs:
  checks:
    env:
      CI: true
    name: checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install and build
        run: npm ci

      - name: Lint
        run: npm run style

  publish:
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    needs: checks
    env:
      CI: true
    name: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15.x"

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Configure Git, NPM
        run: |
          git config --global user.email "nilsen.sondre@gmail.com"
          git config --global user.name "Sondre Nilsen" 
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Prepare repository
        run: |
          git checkout "${GITHUB_REF:11}"
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GH_TOKEN }}

      - name: Publish
        run: |
          npm ci
          npm run ci:publish
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_GH_TOKEN }}
