name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    environment: release
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6.0.0

      - uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install and build
        run: pnpm install

      - name: Lint
        run: pnpm run format

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
